language: python
services:
python:
  - "2.7"
install:
  - pip install .
sccript:
  - python setup.py test
notifications:
  email:
    recipients:
      - andre@merzky.net
    on_success: change
    on_failure: always
