# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

services:

python:
  - "2.7"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
#  - pip install --upgrade pip setuptools
#  - pip install pytest pytest-cov
#  - pip install numpy
  - pip install codecov
#  - pip install -e .

install:
  - pip install .

script:
  - pwd
  - ls -a
  - pip install nose coverage
  - python setup.py test

notifications:
  email:
    recipients:
      - andre@merzky.net
    on_success: change
    on_failure: always

after_success:
  - codecov

