# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

services:

python:
  - "2.7"

before_install:
  - pwd
  - ls -a
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools
  - pip install codecov
  - pip install nose coverage


install:
  - pip install .

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - andre@merzky.net
    on_success: change
    on_failure: always

after_success:
  - codecov
